---
- name: Generate .network configuration files
  template:
    src: systemd_networkd_config.j2
    dest: "/etc/systemd/network/{{ item.key }}.network"
    owner: root
    group: systemd-network
    mode: 0640
  loop: "{{ systemd_network | dict2items }}"
  notify: Restart systemd-networkd

- name: Generate .netdev configuration files
  template:
    src: systemd_networkd_config.j2
    dest: "/etc/systemd/network/{{ item.key }}.netdev"
    owner: root
    group: systemd-network
    mode: 0640
  loop: "{{ systemd_netdev | dict2items }}"
  notify: Restart systemd-networkd

- name: Generate .link configuration files
  template:
    src: systemd_networkd_config.j2
    dest: "/etc/systemd/network/{{ item.key }}.link"
    owner: root
    group: systemd-network
    mode: 0640
  loop: "{{ systemd_link | dict2items }}"
  notify: Restart systemd-networkd
